-- Copyright © 2023, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
-- SPDX-License-Identifier: Apache-2.0

create schema api;

create role anon nologin;

grant usage on schema api to anon;
 
-- Schema below was adapted from: https://postgrest.org/en/stable/references/api/resource_embedding.html#relationships
CREATE TABLE api.actors(
  id int primary key generated by default as identity,
  first_name text,
  last_name text
);

CREATE TABLE api.directors(
  id int primary key generated by default as identity,
  first_name text,
  last_name text
);

CREATE TABLE api.films(
  id int primary key generated by default as identity,
  director_id int references api.directors(id),
  title text,
  year int,
  rating numeric(3,1),
  language text
);

CREATE TABLE api.technical_specs(
  film_id INT REFERENCES api.films UNIQUE,
  runtime TIME,
  camera TEXT,
  sound TEXT
);

CREATE TABLE api.roles(
  film_id int references api.films(id),
  actor_id int references api.actors(id),
  character text,
  primary key(film_id, actor_id)
);

CREATE TABLE api.competitions(
  id int primary key generated by default as identity,
  name text,
  year int
);

CREATE TABLE api.nominations(
  competition_id int references api.competitions(id),
  film_id int references api.films(id),
  rank int,
  primary key (competition_id, film_id)
);


CREATE TYPE api.coordinates as (
  lat decimal(8,6),
  lng decimal(9,6)
);

CREATE TABLE api.countries (
  id int generated by default as identity,
  location api.coordinates,
  languages text[],
  primary key(id)
);

CREATE Table api.people (
  id int generated by default as identity,
  json_data jsonb,
  primary key(id)
);

CREATE TABLE api.empty (
  id int generated by default as identity,
  primary key(id)
);

-- adapted from https://postgrest.org/en/stable/references/api/tables_views.html#bulk-insert-with-default-values
CREATE TABLE api.foo (
  id int generated by default as identity,
  bar text default 'bar',
  baz int default 100 not null,
  primary key(id)
);

insert into api.competitions (name, year) values ('Academy Awards', 1973);

insert into api.directors (first_name, last_name)
values ('Frank', 'Darabont'), ('Francis', 'Coppola'), ('Christopher', 'Nolan');

insert into api.films (title, director_id, year)
values ('The Shawshank Redemption', 1, 1994), ('The Godfather', 2, 1972), ('The Dark Knight', 3, 2008), ('The Godfather Part II', 2, 1974);

insert into api.actors (first_name, last_name)
values ('Marlon', 'Brando'), ('Al', 'Pacino'), ('Robert', 'De Niro');

insert into api.roles (actor_id, film_id, character)
values (1, 2, 'Don Vito Corleone'), (2, 2, 'Michael Corleone'), (2, 4, 'Michael Corleone'), (3, 4, 'Vito Corleone');

insert into api.technical_specs (film_id, runtime, camera, sound) values (2, '02:55', 'Arriflex 35-III', 'mono');

insert into api.nominations (competition_id, film_id, rank) values(1, 2, 1);


insert into api.countries (location, languages) values ('(1.1, 2.2)', array['en']);

insert into api.people (json_data) values
('{ "blood_type": "A-", "age": 18, "phones": [{"country_code": 61, "number": "917-929-5745"}] }'),
('{ "blood_type": "O+", "age": 28, "phones": [{"country_code": 43, "number": "512-446-4988"}, {"country_code": 43, "number": "213-891-5979"}] }');

grant all privileges on api.directors to anon;
grant all privileges on api.actors to anon;
grant all privileges on api.films to anon;
grant all privileges on api.roles to anon;
grant all privileges on api.technical_specs to anon;
grant all privileges on api.competitions to anon;
grant all privileges on api.nominations to anon;
grant all privileges on api.countries to anon;
grant all privileges on api.people to anon;
grant all privileges on api.empty to anon;
grant all privileges on api.foo to anon;

