# Copyright © 2023, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

name: Code quality check

on: pull_request

jobs:
  prettify-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: current
      - name: Install dependencies
        run: npm ci
      - name: Run Prettify check
        run: npm run format:check
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: current
      - name: Install dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint
  circular-deps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: current
      - name: Install dependencies
        run: npm ci
      - name: Run Circular deps check
        run: npm run circular-deps
  test:
    runs-on: ubuntu-latest
    container:
      image: node
      options: --user node
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test:ci -- --coverage
